---
version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD

  rspec:
    image: $TAG_COMMIT_PATH
    container_name: rspec
    entrypoint: ["./docker-scripts/rspec-entrypoint.sh"]
    depends_on:
      - db-test
    environment:
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_HOST: db-test
      DATABASE_USERNAME: $DATABASE_USERNAME
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      RAILS_ENV: test

  db-test:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
